
title: Longeve
# name?
# tagline:
# description:
# logo:

lang: en_EU
timezone: UTC

twitter:
  username: longeve
  # card: summary

# host: longeve.com
url: "https://longeve.com"
# baseurl: ""

# google_site_verification:
# webmaster_verifications:
#   google:

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["autolink", "table"]
# https://github.com/gjtorikian/commonmarker

optional_front_matter:
  remove_originals: true
titles_from_headings:
  strip_title: false
